// <auto-generated />
using System;
using BRK0Y5_HSZF_2024252.Persistence.MsSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BRK0Y5_HSZF_2024252.Persistence.MsSql.Migrations
{
    [DbContext(typeof(TaxiDbContext))]
    [Migration("20250429180936_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("BRK0Y5_HSZF_2024252.Model.Fare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FareStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxiCarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaxiCarId");

                    b.ToTable("Fares");
                });

            modelBuilder.Entity("BRK0Y5_HSZF_2024252.Model.TaxiCar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaxiCars");
                });

            modelBuilder.Entity("BRK0Y5_HSZF_2024252.Model.Fare", b =>
                {
                    b.HasOne("BRK0Y5_HSZF_2024252.Model.TaxiCar", "Car")
                        .WithMany("Fares")
                        .HasForeignKey("TaxiCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("BRK0Y5_HSZF_2024252.Model.TaxiCar", b =>
                {
                    b.Navigation("Fares");
                });
#pragma warning restore 612, 618
        }
    }
}
